---
title: "p8105_hw2_ac4964"
author: "AnMei Chen"
date: "10/1/2021"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(dplyr)
```

# Problem 1

Read and clean the Mr.Trash Wheel sheet

```{r}
Mr_trash_df = 
  read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",sheet = "Mr. Trash Wheel", range = "A2:N406") %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(
    sports_balls = round(sports_balls,digits = 0)
  )
  
```


Read and clean precipitation data for 2018 and 2019

```{r}
Precipitation_2018_df = 
  read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",sheet = "2018 Precipitation", range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  mutate(year = "2018") %>% 
  relocate(year)

Precipitation_2019_df = 
  read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",sheet = "2019 Precipitation", range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  mutate(year = "2019") %>% 
  relocate(year)
```


Combine 2018 and 2019 precipitation datasets

```{r}
Precipitations_df = 
  bind_rows(Precipitation_2018_df,Precipitation_2019_df) %>% 
  mutate( month = month.name[month])
```



